name: Alerta de push

on:
  push:
    branches: [ main ]

jobs:
  alerta:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta
        uses: rtCamp/action-slack-notify@v2.0.0
        with:
          status: 'success'
          message: 'Se ha hecho un push en el repositorio.'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
