name: Alerta de push

on:
  push:
    branches: main 

jobs:
  alerta:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta
        with:
          status: 'success'
          message: 'Se ha hecho un push en el repositorio.'
        env:
          run: | 
            echo "La prueba es exitosa"
